---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ruochen.
--- DateTime: 2018/6/22 23:24
---

local KeyBind = {}

KeyBind[27] = "ESC"
KeyBind[119] = "W"
KeyBind[115] = "S"
KeyBind[97] = "A"
KeyBind[100] = "D"
return KeyBind