---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ruochen.
--- DateTime: 2018/6/22 23:24
---

local KeyBind = {}

KeyBind[27] = "ESC"

KeyBind[97] = "a"
KeyBind[98] = "b"
KeyBind[99] = "c"
KeyBind[100] = "d"
KeyBind[101] = "e"
KeyBind[102] = "f"
KeyBind[103] = "g"
KeyBind[104] = "h"
KeyBind[105] = "i"
KeyBind[106] = "j"
KeyBind[107] = "k"
KeyBind[108] = "l"
KeyBind[109] = "m"
KeyBind[110] = "n"
KeyBind[111] = "o"
KeyBind[112] = "p"
KeyBind[113] = "q"
KeyBind[114] = "r"
KeyBind[115] = "s"
KeyBind[116] = "t"
KeyBind[117] = "u"
KeyBind[118] = "v"
KeyBind[119] = "w"
KeyBind[120] = "x"
KeyBind[121] = "y"
KeyBind[122] = "z"

KeyBind[768] = "k_down"
KeyBind[769] = "k_up"

KeyBind[1024] = "m_motion"
KeyBind[1025] = "m_down"
KeyBind[1026] = "m_up"

KeyBind[1] = "m_left"
KeyBind[3] = "m_right"

return KeyBind